### ISSUE TITLE
AWS "credentials not set" in test environment when using SSM

### ISSUE THREAD

**Issue by esmarkowski** [boltops-tools/jets#612]
## Checklist

- [ x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |      MacOS 11.6   |
| Jets             |  3.0.22       |
| Ruby             |     2.7.1p83    |

---

## Expected Behaviour

SSM replacement or access to necessary AWS resources even in test. 

## Current Behavior

When global .env references SSM variables Jets errors when running tests. 

## Step-by-step reproduction instructions

```
# .env
SOMEVAR=SSM # gets expanded to /app-name/jets-env/SOMEVAR
```

### Run a test

```
bundle exec rspec
```

```
An error occurred while loading spec_helper.
Failure/Error: Jets.boot

Aws::Errors::MissingCredentialsError:
  unable to sign request without credentials set

...

# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/aws-sdk-ssm-1.126.0/lib/aws-sdk-ssm/client.rb:6230:in `get_parameter'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/dotenv/ssm.rb:43:in `fetch_ssm_value'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/dotenv/ssm.rb:15:in `block in interpolate!'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/dotenv/ssm.rb:13:in `each'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/dotenv/ssm.rb:13:in `map'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/dotenv/ssm.rb:13:in `interpolate!'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/dotenv.rb:15:in `load!'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/dotenv.rb:5:in `load!'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/application.rb:75:in `load_default_config'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/application.rb:15:in `setup!'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/booter.rb:12:in `boot!'
# /Users/spencer/.rvm/gems/ruby-2.7.1/gems/jets-3.0.22/lib/jets/core.rb:18:in `boot'
```

## Solution Suggestion

Currently, Jets::AwsInfo#account returns a fake value if the environment is test. Optionally allow test environment to use AWS account like other environments.

This would allow: 
- SSM replacement during tests
- Access to custom AWS Resources or polymorphic lambda functions needed during testing
- Better integration tests across AWS infrastructure

Ideally, I feel like being able to specify which AWS resources should use stub vs real accounts would be nice. However, a simple solution might be to allow override via ENV['JETS_AWS_ACCOUNT'] if present. 

_lib/jets/aws_info.rb_
```ruby
    def account
      return ENV['JETS_AWS_ACCOUNT'] || '123456789' if Jets.env.test?

      # ensure region set, required for sts.get_caller_identity.account to work
      ENV['AWS_REGION'] ||= region
      begin
        sts.get_caller_identity.account
      rescue Aws::Errors::MissingCredentialsError, Aws::Errors::NoSuchEndpointError, Aws::STS::Errors::InvalidClientTokenId
        puts "INFO: You're missing AWS credentials. Only local services are currently available"
      rescue Seahorse::Client::NetworkingError
        puts "INFO: No internet connection available. Only local services are currently available"
      end
    end
    memoize :account

```

**Comment by esmarkowski** [comment]
Commenting out ENV['HOME'] in spec_helper.rb seems lets SSM interpolation happen. It may affect default test behavior, but appears to be an acceptable workaround for my needs. 

_spec/spec_helper.rb_
```ruby
ENV['JETS_TEST'] = "1"
ENV['JETS_ENV'] ||= "test"
# Ensures aws api never called. Fixture home folder does not contain ~/.aws/credentails
# ENV['HOME'] = "spec/fixtures/home"
```

`bundle exec rspec`

SSM Params are available!
